<Project>
  <PropertyGroup>
    <AppVersion>1.1.3</AppVersion>
    <AppVersionWindows>1.1.3.0</AppVersionWindows>
    <WindowsAppSdkVersion>1.6.250402001</WindowsAppSdkVersion>
    <Company>LES</Company>
    <Product>LES Location Agent</Product>
    <Copyright>Copyright © 2026 LES</Copyright>
  </PropertyGroup>
</Project>
